= Документация
:toc:

== Описание программы

Данное приложение написано на языке программирования _C#_ на платформе _WinForms_.

В приложении также есть система навигации по страницам с помощью левой панели навигации.

== Окна приложения

=== Home
В данном окне находится форма для нахождения разницы между датами.

=== Square Equation
В данном окне находится форма для нахождения ответов квадратных уравнений.

=== About
В данном окне находится описание приложения.

=== Add order
В данном окне находится форма добавления заказа как в _MySQL_, так и в _XML_ файл.

=== Read order
В данном окне находится информация о выбранном заказе.

=== Hex info
В данном окне находится форма для просмотра информации о введенном HEX числе:
[cols="1,1"]
|===
|Значение|Описание

|Reversed
|Выводит перевернутое HEX число

|ASCII codes
|Разбивает символы HEX числа на шестнадцатеричные ASCII коды

|As decimal
|Переводит HEX число в десятичную систему счисления
|===

== Пользовательские элементы
=== HexTextBox
Пользовательский элемент HexTextBox - это обычный TextBox,
но который принимает только шестнадцатеричные числа от 0x00 до
любого максимума, по умолчанию 0xFF (при желании, можно установить
максимум вручную через HexTextBox.Maximum = 0xFFFFF).

HexTextBox.Value - шестнадцатеричное число, полученное после ввода
некоторых значений в поле ввода. При желании, можно установить значение
(текст в поле ввода тоже изменится).

=== PriceTextBox
Пользовательский элемент PriceTextBox - это обычный TextBox,
но который принимает только числа (как целые, так и с плавающей точкой).

В элементе справа находится кнопка, по нажатии на которую открывается
диалоговое окно с калькулятором значения. На данный момент реализованы
все функции, кроме сложения, вычитания, деления, умножения и остатка
деления.